### ISSUE TITLE
a few style suggestions before registration

### ISSUE THREAD

**Issue by CarloLucibello** [ianshmean/SystemBenchmark.jl#10]
- The package name could be changed to `SystemBenchmarks` (i.e. plural), following julia guidelines
- avoid camelcase naming,  e.g. `saveBenchmark` could be renamed to `savebenchmark` or `save_benchmark`

**Comment by IanButterworth** [comment]
Thanks. Good point on the camelCase. I’ll fix those errors. 

For the package name, yeah, I think you’re right but I think as it is is also ok. I’m erring I’m leaving it as-is, but I’m open to persuasion

**Comment by IanButterworth** [comment]
camelCase now fixed
